package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;


import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.estimator.PoseEstimator;
import edu.wpi.first.math.estimator.SwerveDrivePoseEstimator;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.PowerDistribution.ModuleType;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.PowerDistribution;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.Constants;
import frc.robot.LimelightHelpers;
import frc.robot.LimelightHelpers.PoseEstimate;
import com.pathplanner.lib.util.DriveFeedforwards;


/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    // VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT 
    // ################################################################################################################################################################################################################
    private boolean doRejectUpdateOne = false;
    private boolean doRejectUpdateTwo = false;

    // Flag for mobing over the bump and change in out pitch or roll
    private boolean bumpFlag = false;

    private boolean hasInitializedYaw = false;

    public RobotConfig config;
    public SwerveRequest request;

    private double[] ambiguitiesOne = {};
    private double[] ambiguitiesTwo = {};

    private double[] oneLLIDs = {};
    private double[] twoLLIDs = {};

    private double ambiguitiesOneAvg = 0;
    private double ambiguitiesTwoAvg = 0;

    private PowerDistribution m_PowerDistributionHub = new PowerDistribution(1, ModuleType.kRev);

    public Translation2d turretCenterOfRotation = new Translation2d(Constants.TurretShooterConstants.turretXOffset, Constants.TurretShooterConstants.turretYOffset); // swap or negate values if rotating over wrong corner
    public Translation2d defaultCenterofRotation = new Translation2d(0, 0);

    public boolean rotOverTurret = false;

    // 18, 27

    // currently 18 is removed
    public int[] validIDs = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32};


    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        setPathPlanner();

    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }


        setPathPlanner();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        setPathPlanner();

    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    // VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT 
    // ################################################################################################################################################################################################################

    public Pose2d getPose2d() {
        return this.getState().Pose;

    }



    public double getXVelocity() {
        return this.getState().Speeds.vxMetersPerSecond;
    }

    public double getYVelocity() {
        return this.getState().Speeds.vyMetersPerSecond;
    }

    public ChassisSpeeds getFieldCentricVelocity() {
        Translation2d turretCenterOfRotation = new Translation2d(Constants.TurretShooterConstants.turretXOffset * Constants.CommandSwerveDrivetrainConstants.rotatingWhileStrafingTestMultiplier, Constants.TurretShooterConstants.turretYOffset * Constants.CommandSwerveDrivetrainConstants.rotatingWhileStrafingTestMultiplier);
        var s = this.getState().Speeds;
        double vx = s.vxMetersPerSecond - s.omegaRadiansPerSecond * turretCenterOfRotation.getY();
        double vy = s.vyMetersPerSecond + s.omegaRadiansPerSecond * turretCenterOfRotation.getX();
        // double vx = s.vxMetersPerSecond;
        // double vy = s.vyMetersPerSecond;
        ChassisSpeeds speeds = ChassisSpeeds.fromRobotRelativeSpeeds(vx, vy, this.getState().Speeds.omegaRadiansPerSecond, this.getState().Pose.getRotation());
        return speeds;
    }

    public double getAngularVelocityDegrees() {
        return Math.toDegrees(this.getState().Speeds.omegaRadiansPerSecond);

    }

    @Override
    public void periodic() {
        doRejectUpdateOne = false;
        doRejectUpdateTwo = false;


        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }


        // VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT VISION MEASUREMENT 
        // ################################################################################################################################################################################################################


        

        if (!hasInitializedYaw) {
            this.seedHeadingWithVision();

            hasInitializedYaw = true;
        }

        LimelightHelpers.SetRobotOrientation("limelight-one", this.getPigeon2().getYaw().getValueAsDouble(), 0, 0, 0, 0, 0);
        LimelightHelpers.PoseEstimate limelightOne_mt1 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-one");
   
        LimelightHelpers.SetFiducialIDFiltersOverride("limelight-one", validIDs);
        
        // if our angular velocity is greater than 360 degrees per second, ignore vision updates
        if(Math.abs(this.getPigeon2().getAngularVelocityZWorld().getValueAsDouble()) > 360) {
            doRejectUpdateOne = true;

        }

        

        if(limelightOne_mt1 == null || limelightOne_mt1.tagCount == 0) {
            doRejectUpdateOne = true;

        }

        LimelightHelpers.SetRobotOrientation("limelight-two", this.getPigeon2().getYaw().getValueAsDouble(), 0, 0, 0, 0, 0);
        LimelightHelpers.PoseEstimate limelightTwo_mt1 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-two");

        LimelightHelpers.SetFiducialIDFiltersOverride("limelight-two", validIDs);


        // if our angular velocity is greater than 360 degrees per second, ignore vision updates
        if(Math.abs(this.getPigeon2().getAngularVelocityZWorld().getValueAsDouble()) > 360) {
            doRejectUpdateTwo = true;

        }

        if(limelightTwo_mt1 == null || limelightTwo_mt1.tagCount == 0) {
            doRejectUpdateTwo = true;

        }

        // maybe use rawFiducials[0].distToCamera > distanceThreshold

        if (limelightOne_mt1 != null &&limelightOne_mt1.avgTagArea < Constants.CommandSwerveDrivetrainConstants.areaThreshold) {
            doRejectUpdateOne = true;
        }

        if (limelightTwo_mt1 != null && limelightTwo_mt1.avgTagArea < Constants.CommandSwerveDrivetrainConstants.areaThreshold) {
            doRejectUpdateTwo = true;
        }

        if (!doRejectUpdateOne && !doRejectUpdateTwo) {
            if (limelightOne_mt1 != null && limelightTwo_mt1 != null && limelightOne_mt1.avgTagArea > limelightTwo_mt1.avgTagArea) {
                doRejectUpdateTwo = true;
            } else {
                doRejectUpdateOne = true;
            }
        }

        // also may not need to iterate through entire array if most of the calculations are taken by order or closest distance or least ambiguity. If that is the case, use rawFudicials[0] only to reject update

        if (limelightOne_mt1 != null && limelightOne_mt1.rawFiducials != null) {
            oneLLIDs = new double[limelightOne_mt1.rawFiducials.length];
            ambiguitiesOne = new double[limelightOne_mt1.rawFiducials.length];
            ambiguitiesOneAvg = 0;
            for (int i = 0; i < limelightOne_mt1.rawFiducials.length; i++) {
                ambiguitiesOne[i] = limelightOne_mt1.rawFiducials[i].ambiguity;
                oneLLIDs[i] = limelightOne_mt1.rawFiducials[i].id;

                // if (ambiguitiesOne[i] > Constants.CommandSwerveDrivetrainConstants.ambiguityThreshold) {
                //     doRejectUpdateOne = true;
                // }
                ambiguitiesOneAvg += ambiguitiesOne[i];
            }
            ambiguitiesOneAvg /= limelightOne_mt1.rawFiducials.length;
            if (ambiguitiesOneAvg > Constants.CommandSwerveDrivetrainConstants.ambiguityThreshold) {
                doRejectUpdateOne = true;
            }
        }

        if (limelightTwo_mt1 != null && limelightTwo_mt1.rawFiducials != null) {
            twoLLIDs = new double[limelightTwo_mt1.rawFiducials.length];
            ambiguitiesTwo = new double[limelightTwo_mt1.rawFiducials.length];
            ambiguitiesTwoAvg = 0;
            for (int i = 0; i < limelightTwo_mt1.rawFiducials.length; i++) {
                ambiguitiesTwo[i] = limelightTwo_mt1.rawFiducials[i].ambiguity;
                twoLLIDs[i] = limelightTwo_mt1.rawFiducials[i].id;

                // if (ambiguitiesTwo[i] > Constants.CommandSwerveDrivetrainConstants.ambiguityThreshold) {
                //     doRejectUpdateTwo = true;
                // }
                ambiguitiesTwoAvg += ambiguitiesTwo[i];
            }
            ambiguitiesTwoAvg /= limelightTwo_mt1.rawFiducials.length;

            if (ambiguitiesTwoAvg > Constants.CommandSwerveDrivetrainConstants.ambiguityThreshold) {
                doRejectUpdateTwo = true;
            }
        }

        if(!doRejectUpdateOne) {
            this.setVisionMeasurementStdDevs(VecBuilder.fill(Constants.CommandSwerveDrivetrainConstants.limelightStdDevs, Constants.CommandSwerveDrivetrainConstants.limelightStdDevs, Constants.CommandSwerveDrivetrainConstants.limelightStdDevs));
            this.addVisionMeasurement(
                limelightOne_mt1.pose,
                limelightOne_mt1.timestampSeconds);
            
            // seedHeadingWithVision(limelightOne_mt1);

        }

        if(!doRejectUpdateTwo) {
            this.setVisionMeasurementStdDevs(VecBuilder.fill(Constants.CommandSwerveDrivetrainConstants.limelightStdDevs, Constants.CommandSwerveDrivetrainConstants.limelightStdDevs, Constants.CommandSwerveDrivetrainConstants.limelightStdDevs));
            this.addVisionMeasurement(
                limelightTwo_mt1.pose,
                limelightTwo_mt1.timestampSeconds);

            // seedHeadingWithVision(limelightTwo_mt1);
        }
        checkPitchAndRoll();
        updateSmartDashboard();

    }

    public ChassisSpeeds getChassisSpeeds() {
        return this.getState().Speeds;
    }

    public void resetPose(Pose2d pose) {
        this.seedHeadingWithVision();
    }

    public void setSpeeds(ChassisSpeeds speed, DriveFeedforwards feedforwards) {
        request = new SwerveRequest.ApplyRobotSpeeds().withSpeeds(speed).withCenterOfRotation(rotOverTurret ? turretCenterOfRotation : defaultCenterofRotation);
        this.setControl(request);

    }

    public void setRotOverTurret(boolean rotOverTurret) {
        this.rotOverTurret = rotOverTurret;
    }

    private void setPathPlanner() {
        
        // Load the RobotConfig from the GUI settings. You should probably
        // store this in your Constants file
        try{
        config = RobotConfig.fromGUISettings();
        } catch (Exception e) {
        // Handle exception as needed
        e.printStackTrace();
        }

        // Configure AutoBuilder last
        AutoBuilder.configure(
                this::getPose2d, // Robot pose supplier
                this::resetPose, // Method to reset odometry (will be called if your auto has a starting pose)
                this::getChassisSpeeds, // ChassisSpeeds supplier. MUST BE ROBOT RELATIVE
                this::setSpeeds, // Method that will drive the robot given ROBOT RELATIVE ChassisSpeeds. Also optionally outputs individual module feedforwards
                new PPHolonomicDriveController( // PPHolonomicController is the built in path following controller for holonomic drive trains
                        new PIDConstants(3.0, 0.0, 0.4), // Translation PID constants
                        new PIDConstants(3.5, 0.0, 0.17) // Rotation PID constants
                ),
                config, // The robot configuration
                () -> {
                // Boolean supplier that controls when the path will be mirrored for the red alliance
                // This will flip the path being followed to the red side of the field.
                // THE ORIGIN WILL REMAIN ON THE BLUE SIDE

                Optional<DriverStation.Alliance> alliance = DriverStation.getAlliance();
                if (alliance.isPresent()) {
                    return alliance.get() == DriverStation.Alliance.Red;
                }
                return false;
                },
                this // Reference to this subsystem to set requirements
        );
    }

    public void seedHeadingWithVision() {
        LimelightHelpers.PoseEstimate limelightOne_mt1 = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-one");
        LimelightHelpers.PoseEstimate limelightTwo_mt1 = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-two");
        if (limelightOne_mt1 != null && limelightOne_mt1.tagCount >= 1) {
            this.resetRotation(limelightOne_mt1.pose.getRotation());
            this.getPigeon2().setYaw(limelightOne_mt1.pose.getRotation().getDegrees());
        }
        else if (limelightTwo_mt1 != null && limelightTwo_mt1.tagCount >= 1) {
            this.resetRotation(limelightTwo_mt1.pose.getRotation());
            this.getPigeon2().setYaw(limelightTwo_mt1.pose.getRotation().getDegrees());
        }

        if (limelightOne_mt1 != null && limelightOne_mt1.tagCount >= 1) {
            this.resetRotation(limelightOne_mt1.pose.getRotation());
            this.getPigeon2().setYaw(limelightOne_mt1.pose.getRotation().getDegrees());
        }
        else if (limelightTwo_mt1 != null && limelightTwo_mt1.tagCount >= 1) {
            this.resetRotation(limelightTwo_mt1.pose.getRotation());
            this.getPigeon2().setYaw(limelightTwo_mt1.pose.getRotation().getDegrees());
        }

        // this.getPigeon2().setYaw(this.getState().Pose.getRotation().getDegrees());
    }

    // public boolean getLLUpdates() {
    //     LimelightHelpers.PoseEstimate limelightOne_mt1 = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-one");
    //     LimelightHelpers.PoseEstimate limelightTwo_mt1 = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-two");
    //     if (limelightOne_mt1 == null || limelightTwo_mt1 == null)
    //         return !doRejectUpdateOne || !doRejectUpdateTwo;
    //     else {return false;}
    // }


    private void updateSmartDashboard() {
        SmartDashboard.putNumber("Robot Yaw", this.getPigeon2().getYaw().getValueAsDouble());

        SmartDashboard.putBoolean("LL ONE UPDATE", !doRejectUpdateOne);
        SmartDashboard.putBoolean("LL TWO UPDATE", !doRejectUpdateTwo);

        SmartDashboard.putBoolean("Bump Flag", bumpFlag);

        SmartDashboard.putBoolean("limelightOne_mt1 null or tagCount == 0)", (LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-one") == null || LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-one").tagCount == 0));
        SmartDashboard.putBoolean("limelightTwo_mt1 null or tagCount == 0)", (LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-two") == null || LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-two").tagCount == 0));

        SmartDashboard.putBoolean("getAngularVelocityZWorld", this.getPigeon2().getAngularVelocityZWorld().getValueAsDouble() > 360);

        SmartDashboard.putNumber("limelightOne_mt1 avgTagArea", LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-one") != null ? LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-one").avgTagArea : 0);
        SmartDashboard.putNumber("limelightTwo_mt1 avgTagArea", LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-two") != null ? LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-two").avgTagArea : 0);
        
        SmartDashboard.putNumberArray("limelightOne ambiguities", ambiguitiesOne);
        SmartDashboard.putNumberArray("limelightTwo ambiguities", ambiguitiesTwo);

        SmartDashboard.putNumberArray("limelightOne IDs", oneLLIDs);
        SmartDashboard.putNumberArray("limelightTwo IDs", twoLLIDs);

        SmartDashboard.putNumber("ambiguitiesOneAvg", ambiguitiesOneAvg);
        SmartDashboard.putNumber("ambiguitiesTwoAvg", ambiguitiesTwoAvg);

        SmartDashboard.putNumber("totalPDHCurrent", m_PowerDistributionHub.getTotalCurrent());
        SmartDashboard.putNumber("totalPDH", m_PowerDistributionHub.getTotalPower());
        SmartDashboard.putNumber("totalPDHVoltage", m_PowerDistributionHub.getVoltage());

        // for (int i = 0; i < 24; i++) {
        //     SmartDashboard.putNumber("PDH Channel: " + i, m_PowerDistributionHub.getCurrent(i));
        // }

    }

    public void saveRecording() {
        LimelightHelpers.triggerRewindCapture("limelight-one", 164);
        LimelightHelpers.triggerRewindCapture("limelight-two", 164);
    }

    private void checkPitchAndRoll() {
        LimelightHelpers.PoseEstimate limelightOne_mt1 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-one");

        double pitch = this.getPigeon2().getPitch().getValueAsDouble();
        double roll = this.getPigeon2().getPitch().getValueAsDouble();

        if (bumpFlag)
            if (pitch <= TunerConstants.pitchDeadzone && roll <= TunerConstants.rollDeadzone)
                if (limelightOne_mt1 != null && limelightOne_mt1.tagCount != 0) {
                    bumpFlag = false;
                    seedHeadingWithVision();
                }
        else
            if (pitch > TunerConstants.pitchDeadzone || roll >= TunerConstants.rollDeadzone)
                bumpFlag = true;
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}
